// <auto-generated />
namespace DevOps.GitMergeSwirl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class t7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t7));
        
        string IMigrationMetadata.Id
        {
            get { return "201603120517352_t7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
